version: '3.1'
services:
  app:
    image: iamusayev/bk:3.0
    restart: always
    ports:
      - 8088:8085
    depends_on:
      - db
    environment:
      DB_CONNECTION_IP: db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5437:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
